### ISSUE TITLE
Missing scripts

### ISSUE THREAD

**Issue by chgaul** [HySonLab/Multires-Graph-Transformer#1]
Dear authors,

Congratulations for your paper and thanks for sharing your code!

I just wanted to try it and noticed that apparently some files are missing. If I follow the readme and execute, for example,
`sh scripts/train_polymer.sh `
then I get the following error:
`python3: can't open file '$HOME/Multires-Graph-Transformer/train_polymer.py': [Errno 2] No such file or directory`

Could you please add the missing files to the repository?

**Comment by nnkhang19** [comment]
We apologize for this mistake. The training files written in Python were accidentally deleted while we were cleaning our code. We just uploaded them back to the repository. Now, you can run the command again. Thanks for raising this issue with us.

**Comment by chgaul** [comment]
Thank you very much for the scripts, and also for uploading the polymer dataset, which was not there before!

I have been trying it out today. I found that some minor fixes are needed to actually run the code (train_peptides_func.sh, train_peptides_struct.sh, and train_polymer.sh; for the new train_lba.sh data seems to be missing).

Feel free to check out my fork at [chgaul/Multires-Graph-Transformer](https://github.com/chgaul/Multires-Graph-Transformer).
